[package]
name = "reactive-graph-runtime-graphql-web"
description = "Inexor - Reactive Graph Flow - Runtime - GraphQL - Web"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../../../README.md"

[dependencies]
actix-web = { workspace = true }
async-graphql = { workspace = true }
async-graphql-actix-web = { workspace = true }

reactive-graph-runtime-graphql-schema = { version = "0.10.0", path = "../schema" }

[lib]
crate-type = ["lib"]
