[package]
name = "reactive-graph-remotes-model"
description = "Reactive Graph - Remotes - Model"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../../../README.md"

[dependencies]
chrono = { workspace = true }
serde = { workspace = true, features = ["derive"] }
typed-builder = { workspace = true }

[lib]
crate-type = ["lib"]
