[package]
name = "reactive-graph-reactive-model-api"
description = "Reactive Graph - Reactive Model - API"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../../../../README.md"

[dependencies]
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }

reactive-graph-graph = { version = "0.10.0", path = "../../../graph" }

[dev-dependencies]
reactive-graph-test-utils = { version = "0.10.0", path = "../../../test-utils" }

[lib]
crate-type = ["lib"]
