[package]
name = "reactive-graph-type-system-rest"
description = "Reactive Graph - Type System - REST API"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../../README.md"

[dependencies]
actix-web = { workspace = true, features = ["rustls-0_23"] }
mime = { workspace = true }

reactive-graph-graph = { version = "0.10.0", path = "../../graph" }
reactive-graph-type-system-api = { version = "0.10.0", path = "../api" }

[lib]
crate-type = ["lib"]
