[package]
name = "reactive-graph-generator-codegen"
description = "Reactive Graph - Generator - Code Generation"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../../../README.md"

[dependencies]
anyhow = { workspace = true }
convert_case = { workspace = true }
dashmap = { workspace = true }
json5 = { workspace = true, optional = true }
prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
# replacer = "0.4.0"
serde = { workspace = true }
serde_json = { workspace = true }
semver = { workspace = true }
syn = { workspace = true }
toml = { workspace = true, optional = true }
typed-builder = { workspace = true }
thiserror = { workspace = true }
workspace_root = { workspace = true }

reactive-graph-graph = { version = "0.10.0", path = "../../graph" }
reactive-graph-generator-documentation = { version = "0.10.0", path = "../../generator/documentation" }

[dev-dependencies]
# default-test = { workspace = true }

reactive-graph-graph = { version = "0.10.0", path = "../../graph", features = ["test"] }
reactive-graph-utils-test = { version = "0.10.0", path = "../../utils/test" }

[lib]
crate-type = ["lib"]

[lints]
workspace = true
