[package]
name = "reactive-graph-type-system-json-schema"
description = "Reactive Graph - Type System - JSON Schema"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../../README.md"

[dependencies]
actix-web = { workspace = true, features = ["rustls-0_23"] }
schemars = { workspace = true, features = ["uuid1"] }

reactive-graph-graph = { version = "0.10.0", path = "../../graph" }

[lib]
crate-type = ["lib"]
